fixtures:
  repositories:
    mount_core:
      repo: https://github.com/puppetlabs/puppetlabs-mount_core.git
      ref: 1.0.4
      puppet_version: ">= 6.0.0"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      ref: 1.0.1
      puppet_version: ">= 6.0.0"
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.25.1
    firewall:
      repo: https://github.com/puppetlabs/puppetlabs-firewall.git
      ref: 1.0.2
    mysql:
      repo: https://github.com/puppetlabs/puppetlabs-mysql.git
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
    augeasproviders_core:
      repo: https://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_sysctl:
      repo: https://github.com/hercules-team/augeasproviders_sysctl.git
    logrotate:
      repo: https://github.com/voxpupuli/puppet-logrotate.git
    epel:
      repo: https://github.com/stahnma/puppet-module-epel.git
    limits:
      repo: https://github.com/saz/puppet-limits.git
    munge:
      repo: https://github.com/treydock/puppet-munge.git
    systemd:
      repo: https://github.com/camptocamp/puppet-systemd.git
    rsyslog:
      repo: https://github.com/saz/puppet-rsyslog.git
  symlinks:
    slurm: "#{source_dir}"
    site_slurm: "#{File.join(source_dir, 'spec/fixtures', 'site_slurm')}"
