# Private class
class slurm::params {

  $spank_plugins          = {}

  $slurm_conf_override    = {}
  $partitionlist          = []
  $slurmdbd_conf_override = {}

  $service_ulimits        = [
    '-l unlimited',
    '-n 8192',
  ]

  $cgroup_allowed_devices = [
    '/dev/null',
    '/dev/urandom',
    '/dev/zero',
    '/dev/sda*',
    '/dev/cpu/*/*',
    '/dev/pts/*',
  ]

  $slurm_conf_defaults = {
    '14.03' => {
      'AccountingStorageType' => 'accounting_storage/slurmdbd',
      'AccountingStoreJobComment' => 'YES',
      'AuthType' => 'auth/munge',
      'CacheGroups' => '0',
      'CheckpointType' => 'checkpoint/none',
      'CompleteWait' => '0',
      'CryptoType' => 'crypto/munge',
      'DefaultStorageType' => 'slurmdbd',
      'DisableRootJobs' => 'NO',
      'EpilogMsgTime' => '2000',
      'FastSchedule' => '1',
      'FirstJobId' => '1',
      'GetEnvTimeout' => '2',
      'GroupUpdateForce' => '0',
      'GroupUpdateTime' => '600',
      'HealthCheckInterval' => '0',
      'HealthCheckNodeState' => 'ANY',
      'InactiveLimit' => '0',
      'JobAcctGatherFrequency' => 'task=30',
      'JobAcctGatherType' => 'jobacct_gather/linux',
      'JobCompType' => 'jobcomp/none',
      'JobRequeue' => '1',
      'KillOnBadExit' => '0',
      'KillWait' => '30',
      'MailProg' => '/bin/mail',
      'MaxArraySize' => '1001',
      'MaxJobCount' => '10000',
      'MaxJobId' => '4294901760',
      'MaxMemPerCPU' => '0',
      'MaxMemPerNode' => '0',
      'MaxStepCount' => '40000',
      'MaxTasksPerNode' => '128',
      'MessageTimeout' => '10',
      'MinJobAge' => '300',
      'MpiDefault' => 'none',
      'OverTimeLimit' => '0',
      'PluginDir' => '/usr/lib64/slurm',
      'PreemptMode' => 'OFF',
      'PreemptType' => 'preempt/none',
      'PriorityType' => 'priority/basic',
      'ProctrackType' => 'proctrack/pgid',
      'PropagatePrioProcess' => '0',
      'PropagateResourceLimits' => 'ALL',
      'ResvOverRun' => '0',
      'ReturnToService' => '0',
      'SchedulerTimeSlice' => '30',
      'SchedulerType' => 'sched/backfill',
      'SelectType' => 'select/linear',
      'SlurmctldDebug' => 'info',
      'SlurmctldTimeout' => '120',
      'SlurmdDebug' => 'info',
      'SlurmdTimeout' => '300',
      'SlurmSchedLogLevel' => '0',
      'SwitchType' => 'switch/none',
      'TaskPlugin' => 'task/none',
      'TmpFS' => '/tmp',
      'TopologyPlugin'  => 'topology/none',
      'TrackWCKey' => 'no',
      'TreeWidth' => '50',
      'UsePAM' => '0',
      'VSizeFactor' => '0',
      'WaitTime' => '0',
    },
    '14.11' => {
      'AccountingStorageType' => 'accounting_storage/slurmdbd',
      'AccountingStoreJobComment' => 'YES',
      'AllowSpecResourcesUsage' => '0',
      'AuthType' => 'auth/munge',
      'CacheGroups' => '0',
      'CheckpointType' => 'checkpoint/none',
      'CompleteWait' => '0',
      'CpuFreqDef' => 'OnDemand',
      'CryptoType' => 'crypto/munge',
      'DefaultStorageType' => 'slurmdbd',
      'DisableRootJobs' => 'NO',
      'EpilogMsgTime' => '2000',
      'FastSchedule' => '1',
      'FirstJobId' => '1',
      'GetEnvTimeout' => '2',
      'GroupUpdateForce' => '0',
      'GroupUpdateTime' => '600',
      'HealthCheckInterval' => '0',
      'HealthCheckNodeState' => 'ANY',
      'InactiveLimit' => '0',
      'JobAcctGatherFrequency' => 'task=30',
      'JobAcctGatherType' => 'jobacct_gather/linux',
      'JobCompType' => 'jobcomp/none',
      'JobRequeue' => '1',
      'KillOnBadExit' => '0',
      'KillWait' => '30',
      'MailProg' => '/bin/mail',
      'MaxArraySize' => '1001',
      'MaxJobCount' => '10000',
      'MaxJobId' => '4294901760',
      'MaxMemPerCPU' => '0',
      'MaxMemPerNode' => '0',
      'MaxStepCount' => '40000',
      'MaxTasksPerNode' => '128',
      'MemLimitEnforce' => 'yes',
      'MessageTimeout' => '10',
      'MinJobAge' => '300',
      'MpiDefault' => 'none',
      'OverTimeLimit' => '0',
      'PluginDir' => '/usr/lib64/slurm',
      'PreemptMode' => 'OFF',
      'PreemptType' => 'preempt/none',
      'PriorityType' => 'priority/basic',
      'ProctrackType' => 'proctrack/pgid',
      'PropagatePrioProcess' => '0',
      'PropagateResourceLimits' => 'ALL',
      'ResvOverRun' => '0',
      'ReturnToService' => '0',
      'SchedulerTimeSlice' => '30',
      'SchedulerType' => 'sched/backfill',
      'SelectType' => 'select/linear',
      'SlurmctldDebug' => 'info',
      'SlurmctldTimeout' => '120',
      'SlurmdDebug' => 'info',
      'SlurmdTimeout' => '300',
      'SlurmSchedLogLevel' => '0',
      'SwitchType' => 'switch/none',
      'TaskPlugin' => 'task/none',
      'TmpFS' => '/tmp',
      'TopologyPlugin'  => 'topology/none',
      'TrackWCKey' => 'no',
      'TreeWidth' => '50',
      'UsePAM' => '0',
      'VSizeFactor' => '0',
      'WaitTime' => '0',
    },
    '15.08' => {
      'AccountingStorageType' => 'accounting_storage/slurmdbd',
      'AccountingStoreJobComment' => 'YES',
      'AllowSpecResourcesUsage' => '0',
      'AuthType' => 'auth/munge',
      'CacheGroups' => '0',
      'CheckpointType' => 'checkpoint/none',
      'CompleteWait' => '0',
      'CpuFreqDef' => 'OnDemand',
      'CryptoType' => 'crypto/munge',
      'DefaultStorageType' => 'slurmdbd',
      'DisableRootJobs' => 'NO',
      'EpilogMsgTime' => '2000',
      'FastSchedule' => '1',
      'FirstJobId' => '1',
      'GetEnvTimeout' => '2',
      'GroupUpdateForce' => '0',
      'GroupUpdateTime' => '600',
      'HealthCheckInterval' => '0',
      'HealthCheckNodeState' => 'ANY',
      'InactiveLimit' => '0',
      'JobAcctGatherFrequency' => 'task=30',
      'JobAcctGatherType' => 'jobacct_gather/linux',
      'JobCompType' => 'jobcomp/none',
      'JobRequeue' => '1',
      'KillOnBadExit' => '0',
      'KillWait' => '30',
      'MailProg' => '/bin/mail',
      'MaxArraySize' => '1001',
      'MaxJobCount' => '10000',
      'MaxJobId' => '4294901760',
      'MaxMemPerCPU' => '0',
      'MaxMemPerNode' => '0',
      'MaxStepCount' => '40000',
      'MaxTasksPerNode' => '128',
      'MemLimitEnforce' => 'yes',
      'MessageTimeout' => '10',
      'MinJobAge' => '300',
      'MpiDefault' => 'none',
      'OverTimeLimit' => '0',
      'PluginDir' => '/usr/lib64/slurm',
      'PreemptMode' => 'OFF',
      'PreemptType' => 'preempt/none',
      'PriorityType' => 'priority/basic',
      'ProctrackType' => 'proctrack/pgid',
      'PropagatePrioProcess' => '0',
      'PropagateResourceLimits' => 'ALL',
      'ResvOverRun' => '0',
      'ReturnToService' => '0',
      'SchedulerTimeSlice' => '30',
      'SchedulerType' => 'sched/backfill',
      'SelectType' => 'select/linear',
      'SlurmctldDebug' => 'info',
      'SlurmctldTimeout' => '120',
      'SlurmdDebug' => 'info',
      'SlurmdTimeout' => '300',
      'SlurmSchedLogLevel' => '0',
      'SwitchType' => 'switch/none',
      'TaskPlugin' => 'task/none',
      'TmpFS' => '/tmp',
      'TopologyPlugin'  => 'topology/none',
      'TrackWCKey' => 'no',
      'TreeWidth' => '50',
      'UsePAM' => '0',
      'VSizeFactor' => '0',
      'WaitTime' => '0',
    }
  }

  $slurmdbd_conf_defaults = {
    '14.03' => {
      'ArchiveDir' => '/tmp',
      'ArchiveEvents' => 'no',
      'ArchiveJobs' => 'no',
      'ArchiveResvs' => 'no',
      'ArchiveSteps' => 'no',
      'ArchiveSuspend' => 'no',
      'AuthType' => 'auth/munge',
      'DebugLevel' => 'info',
      'MessageTimeout' => '10',
      'PluginDir' => '/usr/lib64/slurm',
      'TrackSlurmctldDown' => 'no',
    },
    '14.11' => {
      'ArchiveDir' => '/tmp',
      'ArchiveEvents' => 'no',
      'ArchiveJobs' => 'no',
      'ArchiveResvs' => 'no',
      'ArchiveSteps' => 'no',
      'ArchiveSuspend' => 'no',
      'AuthType' => 'auth/munge',
      'DebugLevel' => 'info',
      'MessageTimeout' => '10',
      'PluginDir' => '/usr/lib64/slurm',
      'TrackSlurmctldDown' => 'no',
    },
    '15.08' => {
      'ArchiveDir' => '/tmp',
      'ArchiveEvents' => 'no',
      'ArchiveJobs' => 'no',
      'ArchiveResvs' => 'no',
      'ArchiveSteps' => 'no',
      'ArchiveSuspend' => 'no',
      'AuthType' => 'auth/munge',
      'DebugLevel' => 'info',
      'MessageTimeout' => '10',
      'PluginDir' => '/usr/lib64/slurm',
      'TrackSlurmctldDown' => 'no',
    }
  }

  $partition_keys = {
    '14.03' => [
      'PartitionName',
      'Nodes',
      'AllocNodes',
      'Default',
      'Priority',
      'PreemptMode',
      'Shared',
      'MaxNodes',
      'MinNodes',
      'DefaultTime',
      'MaxTime',
      'DefMemPerCPU',
      'MaxMemPerCPU',
      'DefMemPerNode',
      'MaxMemPerNode',
      'AllowGroups',
      'AllowQOS',
      'DisableRootJobs',
      'State',
    ],
    '14.11' => [
      'PartitionName',
      'Nodes',
      'AllocNodes',
      'Default',
      'Priority',
      'PreemptMode',
      'Shared',
      'MaxNodes',
      'MinNodes',
      'DefaultTime',
      'MaxTime',
      'DefMemPerCPU',
      'MaxMemPerCPU',
      'DefMemPerNode',
      'MaxMemPerNode',
      'AllowGroups',
      'AllowQOS',
      'DisableRootJobs',
      'State',
    ],
    '15.08' => [
      'PartitionName',
      'Nodes',
      'AllocNodes',
      'Default',
      'Priority',
      'PreemptMode',
      'Shared',
      'MaxNodes',
      'MinNodes',
      'DefaultTime',
      'MaxTime',
      'DefMemPerCPU',
      'MaxMemPerCPU',
      'DefMemPerNode',
      'MaxMemPerNode',
      'AllowGroups',
      'QOS',
      'AllowQOS',
      'DisableRootJobs',
      'State',
    ],
  }

  case $::osfamily {
    'RedHat': {
      $logrotate_slurm_postrotate     = '/etc/init.d/slurm reconfig >/dev/null 2>&1'
      $logrotate_slurmdbd_postrotate  = '/etc/init.d/slurmdbd reconfig >/dev/null 2>&1'
      $logrotate_syslog_postrotate    = '/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true'
    }

    default: {
      fail("Unsupported osfamily: ${::osfamily}, module ${module_name} only supports osfamily RedHat")
    }
  }

}
